# Generated by Django 4.0.5 on 2023-01-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mystudents',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
                ('clsname', models.CharField(max_length=34)),
                ('marks', models.IntegerField()),
                ('address', models.CharField(max_length=44)),
            ],
        ),
    ]
