# Generated by Django 4.0.5 on 2023-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=30)),
                ('Clsname', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
                ('subject', models.CharField(max_length=44)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
