# Generated by Django 4.0.5 on 2023-01-29 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=44)),
                ('upi_id', models.CharField(max_length=11)),
                ('account_balance', models.IntegerField()),
            ],
        ),
    ]
