# Generated by Django 4.0.5 on 2023-01-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
