# Generated by Django 4.0.5 on 2023-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='upi_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
