# Generated by Django 4.0.5 on 2023-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_users_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account_balance',
            field=models.PositiveBigIntegerField(),
        ),
    ]
