# Generated by Django 4.0.5 on 2023-01-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('clname', models.CharField(max_length=55)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
