# Generated by Django 4.0.5 on 2023-01-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blg_id', models.AutoField(primary_key=True, serialize=False)),
                ('blg_name', models.CharField(max_length=100)),
                ('blg_status', models.BooleanField()),
            ],
        ),
    ]
