# Generated by Django 4.0.5 on 2023-01-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePage',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('Page_name', models.CharField(max_length=44)),
                ('Page_date', models.DateField()),
                ('Page_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mypage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Bk_id', models.AutoField(primary_key=True, serialize=False)),
                ('Book_name', models.CharField(max_length=44)),
                ('Book_pub_date', models.DateField()),
                ('Book_price', models.IntegerField()),
                ('Book_authors', models.ManyToManyField(related_name='mybook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('B_id', models.AutoField(primary_key=True, serialize=False)),
                ('Blog_name', models.CharField(max_length=44)),
                ('Blog_pub_date', models.DateField()),
                ('Blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myblog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
