# Generated by Django 4.0.5 on 2023-01-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctname', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('Pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('Property_name', models.CharField(max_length=100)),
                ('Property_address', models.CharField(max_length=200)),
                ('City_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrApp.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrApp.state'),
        ),
    ]
