# Generated by Django 4.0.5 on 2023-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_customer_storeapp_cu_last_na_36b225_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='storeapp_cu_last_na_36b225_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='user_first_name_for_store',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
