# Generated by Django 4.0.5 on 2023-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=33)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=33)),
                ('roll', models.CharField(max_length=33)),
                ('Address', models.CharField(max_length=200)),
                ('Dob', models.DateField(default='2000-02-12')),
                ('dt', models.DateTimeField(default='2019-09-25 06:00')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=33)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=33)),
                ('Salary', models.CharField(max_length=33)),
                ('Dob', models.DateField(default='2000-02-12')),
            ],
        ),
    ]
