# Generated by Django 4.0.5 on 2023-01-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Dob',
            field=models.DateField(default='2000-02-12'),
        ),
    ]
