# Generated by Django 4.0.5 on 2023-01-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_students_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=33)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=33)),
                ('Salary', models.CharField(max_length=33)),
                ('Dob', models.DateField(default='2000-02-12')),
            ],
        ),
    ]
