# Generated by Django 4.0.5 on 2023-01-05 15:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
    ]
