# Generated by Django 4.0.5 on 2023-01-05 15:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            managers=[
                ('mycustom', django.db.models.manager.Manager()),
            ],
        ),
    ]
