# Generated by Django 4.0.5 on 2023-01-05 16:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0002_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser_proxy',
            fields=[
            ],
            options={
                'ordering': ['age'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cmapp.myuser',),
            managers=[
                ('pr_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
