# Generated by Django 4.0.5 on 2023-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='property',
            field=models.ManyToManyField(to='prapp.propertyowner'),
        ),
    ]
