# Generated by Django 4.0.5 on 2023-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prapp', '0002_ownerdetails_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyowner',
            name='price',
            field=models.IntegerField(),
        ),
    ]
