# Generated by Django 4.0.5 on 2023-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prapp', '0003_alter_propertyowner_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
