# Generated by Django 4.0.5 on 2023-01-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='print',
            new_name='price',
        ),
    ]
