# Generated by Django 4.0.5 on 2023-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstapp', '0002_rename_print_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
