# Generated by Django 4.0.5 on 2023-01-07 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPlayer',
            fields=[
                ('Song_id', models.AutoField(primary_key=True, serialize=False)),
                ('Song_name', models.CharField(max_length=44)),
                ('Song_duration', models.IntegerField()),
                ('Singers_name', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
