# Generated by Django 4.0.5 on 2023-01-06 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade2',
            fields=[
                ('oldtradename', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rdxapp.trade1')),
                ('newtradeprice', models.IntegerField()),
                ('nameofnewtrade', models.CharField(max_length=33)),
            ],
            bases=('rdxapp.trade1',),
        ),
        migrations.AlterField(
            model_name='trade1',
            name='usname',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
